# Generated by Django 2.0.3 on 2018-04-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_link',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
