# Generated by Django 2.0.3 on 2018-04-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0003_auto_20180331_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
