# Generated by Django 2.0.3 on 2018-04-02 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0005_auto_20180331_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date requested'),
        ),
    ]
